import { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import HeaderMenu from "@/components/ui/headermenu";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Weather App</title>
      </head>
      <body className="dark w-full max-w-screen">
      <SidebarProvider>
        <aside>
        <AppSidebar />
        </aside>
        <main className="h-screen overflow-x-auto">
          <HeaderMenu />
          {children}
        </main>
      </SidebarProvider>
      <footer></footer>
      </body>
    </html>
  );
}
